services:
  app:
    image: quyentvk3/book-store:0.0.1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
      JWT_ACCESS_TTL_MINUTES: ${JWT_ACCESS_TTL_MINUTES}
      JWT_REFRESHABLE_TTL_DAYS: ${JWT_REFRESHABLE_TTL_DAYS}
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0.43-debian
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: book_store
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: