server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${SPRING_DATASOURCE_CONNECTION}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

jwt:
  signer-key: ${JWT_SIGNER_KEY}
  access-ttl-minutes: ${JWT_ACCESS_TTL_MINUTES}
  refreshable-ttl-days: ${JWT_REFRESHABLE_TTL_DAYS}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

